# Generated by Django 3.0 on 2022-07-01 12:13

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=random.Random.randint)),
            ],
        ),
    ]
