# Generated by Django 3.0 on 2022-07-01 12:26

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='something',
            name='is_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='something',
            name='number',
            field=models.IntegerField(default=functools.partial(random.Random.randrange, *(0, 100), **{})),
        ),
    ]
